### ISSUE TITLE
clicking should work on phone 

### ISSUE THREAD

**Issue by sallymatson** [stevekrouse/WoofJS#14]

**Comment by stevekrouse** [comment]
This is a perplexing issue, because the mobile alternative to onclick is touchstart, which I am using here https://github.com/stevekrouse/WoofJS/blob/master/woof.es6.js#L107.

There are a few things that could be going wrong here...

1. Touch events aren't getting fired unless you hold for long enough. However, then how are we supposed to capture touch events? We know that you can click on things (like links) on phones, so there must be a way to detect short touches.
2. The touchend event isn't firing properly and it confuses a new touch with the prior touch. This also seems unlikely, but I have a strange sense that I was a little sloppy when I co-opted the touch interface into a clicking interface.
3. The way I did https://github.com/stevekrouse/WoofJS/blob/master/woof.es6.js#L116 is screwing things up.
4. (I think it's this one -- I just realized) I should update the mouseX and mouseY on mousedown (touchstart) and mouseup (touchend). This will probably solve it!

**Comment by stevekrouse** [comment]
@sallymatson this should fix your issue. If you could test it and check if it doesn't fix it and let me know, that'd be great.
