### ISSUE TITLE
woof range() function to replace for-loops entirely

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#318]
For loops are the worst. Wouldn't it be magical if we could do away with them forever?

The solution I have in mind is to create a `range()` function that produces an array that you can forEach over.

It takes 3 params, start, stop (and it stops on stop, not before it, guaranteeing that all numbers in the return array are `>= Math.min(start,stop)` and `<= Math.max(start,stop)`), and step. If stop is more than start, it assumes step is -1, otherwise it assumes step is 1. You can also supply a step/

```javascript
range(1, 5)
=> [1,2,3,4,5]

range(5, 1)
=> [5,4,3,2,1]

range(2, 10, 2)
=> [2,4,6,8,10]
```

This has a few benefits:

1. Not having to learn another syntax when students are already familiar with forEach loops. It also reinforces the forEach syntax.
2. You can easily print out the result of a `range()` as a value so you can see if it does what you inspect. This is a little easier than adding a console log in the body of a for loop.

Lastly, I stole the name "range" from python I think but I'm not in love with it. I'd be super open to other ideas for the name or how the parameters work.

**Comment by stevekrouse** [comment]
There's a large chance this already exists natively in JavaScript or someone has made a library for it already, so it'd make sense to spend some time looking for it.

**Comment by stevekrouse** [comment]
https://lodash.com/docs/4.17.4#range

**Comment by joebeachjoebeach** [comment]
I like this idea, but I want to make sure I'm seeing it the way you are
Does it mean you want to replace this:
```js
for (var i = 0, i < 10, i++) {
  /* code to repeat 10 times */
}
```
with this?:
```js
range(1, 10).forEach(thing => {
  /* code to repeat 10 times */
}
```
If the end goal is repetition of a single block of code, would something like this be more intuitive?:
```js
instantRepeat(10, () => {
  /* code to repeat 10 times */
}
```
I could see how keeping track of the number is useful, by using the `thing` parameter with `forEach()` above, but I guess that could be handled by including a parameter that counts as we go:
```js
instantRepeat(10, i, ()=> {
  /* code to repeat here
  the value of i is set to the repetition number */
}
```

I'm guessing there's a whole class of use-cases that I'm not thinking of, as your example of creating the array `[2, 4, 6, 8, 10]` would clearly be used for something other (more?) than repeating code 5 times.

On a side-note, a third benefit to doing away with for loops has to do with the code editor on create.html -- since it re-runs the code as you edit, you almost always end up with an infinite loop before you can finish typing the first line. For example, when you get this far: `for(var i = 0, i < 10 `, the code runs and you're stuck. I've taken to always typing them out inside a comment first.

**Comment by stevekrouse** [comment]
Ah, I didn't know about the infinite loop problem. That's really terrible... I can't think of a quick solution to that problem other than this one.

Yes, I agree that `instantRepeat` is much more intuitive if you don't need an iterator or the iterator needs to simply go from `1` to `10` increasing by `1` each time.

This range function comes in handy when you need an iterator to go from 10 to -5 by -2's.

In addition to the reasons discussed above, I like this `range` method because it makes it really easy to see exactly how many times your code is running, and with what iterators: `alert(range(10, -5, -2))`. 

I also like this method because it continues to drill the `.forEach` paradigm, which is quite important in JavaScript, most notably with lists of sprites.

**Comment by joebeachjoebeach** [comment]
OK, gotcha. I'll assign myself to this and come back to it when I finish what I'm working on now
