### ISSUE TITLE
make cloning clearer

### ISSUE THREAD

**Issue by joebeachjoebeach** [stevekrouse/WoofJS#336]
Cloning is infamously hard for students, and it's not as straightforward as in Scratch.

Students have conceptual problems with:
1. Not creating their clone-able sprite in the same place they create most of their other sprites
2. Creating an array in which to store sprites, and pushing their clones into that array
3. Using `clones.forEach()` to loop through said array
4. Not having the simplicity of "When I start as a clone"

I think aiming for the Scratch way of doing things is ideal:
- Add something to mirror "Create a clone of myself" from Scratch
- Add something to mirror "When I start as a clone" from Scratch

The branch clone-integration has what I've come up with so far. It addresses numbers 1 through 3 above, but not number 4, and it's not quite as easy to use as I think it could be:
- It stores a copy of the object originally passed to the constructor under the property `sprite._clone`
- It creates an empty array under the property `sprite.clones`
- It adds a method called `sprite.createClone()`, which passes `sprite._clone` into the proper constructor, optionally taking a new object as an argument so you can make the clone different from the original (choose coordinates, size, color, etc), and it pushes the clone into `sprite.clones`
- It adds a method called `sprite.clonesDo()` that hides the `clones.forEach()` behavior from the user

Here's an example of "Rocket Race" using the suggested code:
````
setBackdropURL('./images/outerspace.jpg')

var bird = new Image({
  url: "./docs/images/bird.png",
  width: 50, 
  height: 50,
})

var elephant = new Image({
  url: "./docs/images/elephant.png",
  width: 75, 
  height: 63,
  showing: false
})

var puppy = new Image({
  url: "./docs/images/puppy.png",
  width: 40, 
  height: 55,
  showing: false
})

var score = 0
var scoreBoard = new Text({
  text: () => "Score: " + score,
  x: minX + 35,
  y: maxY - 25,
  color: "white",
  size: 16
})

forever(() => {
  if (keysDown.includes('right')) {
    bird.turnRight(3)
  }
  if (keysDown.includes('left')) {
    bird.turnLeft(3)
  }
  if (keysDown.includes('space')) {
    bird.move(5)
  }
  if (bird.x > maxX + 20) {
    bird.x = minX
  }
  if (bird.x < minX - 20) {
    bird.x = maxX
  }
  if (bird.y > maxY + 20) {
    bird.y = minY
  }
  if (bird.y < minY - 20) {
    bird.y = maxY
  }
})

every(2, 'second', () => {
  elephant.createClone({
    showing: true,
    x: randomX(),
    y: randomY()
  })
})

every(2.5, 'second', () => {
  puppy.createClone({
    showing: true,
    x: randomX(),
    y: randomY()
  })
})

forever(() => {
  elephant.clonesDo((clone) => {
    if (clone.touching(bird)) {
      clone.delete()
      score += 1
    }
  })
  puppy.clonesDo((clone) => {
    if (clone.touching(bird)) {
      freeze()
    }
  })
})
````

**Comment by stevekrouse** [comment]
This is a fun project! Thanks for thinking it through and building out a prototype in the https://github.com/stevekrouse/WoofJS/tree/clone-integration branch.

I think you may be right that "aiming for the Scratch way of doing things is ideal" but I'm not 100% convinced of this so I want to play it out. In many ways, WoofJS is as similar to Scratch as possible so as to make the transition to text-based coding as simple as learning syntax, not having to learn new concepts. So under this way of thinking about things, yes we should make clones as similar to Scratch as possible.

However, I'm not the biggest fan of how clones are implemented in Scratch. In particular, I don't like how you can have an "original sprite" that does stuff and then clones that do their own things. I'd prefer if you had to choose: 1) either you have one sprite that does its thing or 2) you have a number of similar sprites that do the same thing. I don't like combining 1 & 2 into the same structure, which is truly at the heart of what it means to be a clone: an original and a number of copies. So that's why we instruct students to use the "cloning architecture" where they hide the original sprite, have it do nothing, and have the clones to all the real work. If a student doesn't do this, they are doomed to trying to think through an impossibly complex program -- I think it's super important to not let students do this incorrectly. So I'm a little skeptical about mirroring it, where we have them create an original sprite that's hidden and then create clones that are showing, and students have to worry about which is the original sprite versus clones.

**What I like about your proposal**

1. Students don't have to add anything to an array
2. Students can create the original sprite outside of a loop
3. Students can leverage their understanding of Scratch clones
4. The fact that you own the array that clones live in could be helpful. For example, it could let us limit the number of clones students can create like Scratch does for performance reasons. 

**Some problems with your proposal**

1. You lose a significant amount of power when you abstract away arrays from users. It becomes harder to refer to "the first sprite", "the sprite that was created right before me", or use other array functions, like `find()` or `some()`. Of course, you could provide all of those functions to users, but then what you're left with is arrays but with all the functions named specifically for clones. I struggle with this one because on the one hand, I love how we have `forever()` and `every()` loops even though it means that students will one day have to learn that those are really called `setInterval()`. On the other hand, I feel like the JS names for these functions are pretty darn close, so we might as well go with them. However, I could be wrong here and if `clonesDo()` or something like it was easier for students to grasp, I could be convinced.

2. I made two comments but only one of them actually meaningful. It's regarding how you go about cloning technically... https://github.com/stevekrouse/WoofJS/commit/349d886d4dda9dc7031a392dedaa1d69764042bf

**Ideas for trying to make it work with the clones architecture we have now**

1. I think that part of the problem here may be the way that we explain this in the documentation.

![screenshot 2017-03-21 at 2 29 35 pm](https://cloud.githubusercontent.com/assets/2288939/24164045/d6ec0c1a-0e42-11e7-8376-3229c68a5345.png)

a) One way to simplify this is by breaking up the three cloning blocks and having the corresponding JS under each block. 

b) Another would be do take the comments out of the JS code and put more explanation in the documentation above the JS code. Instead of  `// forever, for each clone in clones`, we could say, "If you every clone to do the same thing, you need to use a `.forEach()` loop. A `.forEach()` does the same thing to every thing in a list..."

c) Another option is to make a more clear distinction between Scratch clones and JS objects. For example, we say "There is no wait block in JavaScript. Instead, you can use `after()`" to be as clear as possible that there's a difference from Scratch. We could try not calling similar object "clones" because that's trying to make them seem too similar to Scratch. We could say that there's a JS equivalent to clones but it's different...

2. Maybe we could start by teaching clones without an array to start. Maybe we could have a project where you create a number of similar sprites every X seconds but they don't do anything so you don't need to reference them elsewhere. Maybe they just show up or something. Clones really are as simple as "creating sprites in a loop." Arrays only come into it when you need to refer to them all as a group.

**Other ideas for a new cloning architecture in Woof**

1. As I mentioned at the top of this comment, I would love it if you could create a number of similar objects that aren't clones of an original object. In JS, that's a "class" so we could think about doing this in the class way. A student could create a class that inherits from the `Image` class but has it's own behavior etc. 

2. As you mention, could we have a "when I start as a clone"? This way you won't need arrays because if you want the clones to all do something, you put it in the "when I start as a clone" function. 

```javascript
var rocketFactory = new Factory({
  sprite: Image({...})
  whenIStartAsAClone: function(clone) {...}
})
```

You could also give the user access to the underlying list with `rocketFactory.list` so they could access all of the list methods. Or you could add them to the factory itself like `rocketFactory.find()`

**Comment by stevekrouse** [comment]
My friend Sam from Hopscotch sent me this article on [Star Logo](http://web.mit.edu/mitstep/webdav/Quick%20Start%20Guide/SLTNG%20Quick%20Start%20Guide%20102308.pdf). Instead of a single sprite and clones, StarLogo has the concept of a "class of objects" but it uses the "breed" metaphor. Instead of creating a new single sprite, you create a breed. You can then create as many of that breed as you want, including just one if that's what you want. 

I think the "breed" metaphor could be more powerful for students than the "factory" metaphor I use in the code example above.

```javascript
var rocketBreed = new Breed({
  sprite: Image({...})
  onStart: function(clone) {...}
})
```

**Comment by stevekrouse** [comment]
I had another idea on how to make cloning clearer. It involves reading but I think it could be clearer.

First things first, we stop calling it cloning. More than that we say: **There is NO cloning in Woof** 

Instead, let me show you the woof way to make lots of sprites.

First let's start with one sprite:

```javascript
var unicorn1 = new Image({
  url: "./docs/images/unicorn.png",
  width: 120, 
  height: 80,
})

forever(() => {
  unicorn1.move(1)
})
```

But what if I want another unicorn to be created 1 second later? Copy and paste!

```javascript
var unicorn1 = new Image({
  url: "./docs/images/unicorn.png",
  width: 120, 
  height: 80,
})

forever(() => {
  unicorn1.move(1)
})

after(1, "second", () => {
  var unicorn2 = new Image({
    url: "./docs/images/unicorn.png",
    width: 120, 
    height: 80,
  })

  forever(() => {
    unicorn2.move(1)
  })
})
```

What if we want one more unicorn one second later? Copy and paste again!

```javascript
var unicorn1 = new Image({
  url: "./docs/images/unicorn.png",
  width: 120, 
  height: 80,
})

forever(() => {
  unicorn1.move(1)
})

after(1, "second", () => {
  var unicorn2 = new Image({
    url: "./docs/images/unicorn.png",
    width: 120, 
    height: 80,
  })

  forever(() => {
    unicorn2.move(1)
  })
})
after(2, "seconds", () => {
  var unicorn3 = new Image({
    url: "./docs/images/unicorn.png",
    width: 120, 
    height: 80,
  })

  forever(() => {
    unicorn3.move(1)
  })
})
```

Ok, clearly this can get old. So let's simplify this by creating a list to group the unicorns together. This will let us create one forever loop for all the unicorns.

```javascript
var unicorns = []
var unicorn1 = new Image({
  url: "./docs/images/unicorn.png",
  width: 120, 
  height: 80,
})
unicorns.push(unicorn1)

forever(() => {
  unicorns.forEach(unicorn => {
      unicorn.move(1)
  })
})
```

Now each unicorn in the unicorns list will move appropriate. So we simply have to add the other unicorns to the list to have them move as well.
```javascript
var unicorns = []
var unicorn1 = new Image({
  url: "./docs/images/unicorn.png",
  width: 120, 
  height: 80,
})
unicorns.push(unicorn1)

forever(() => {
  unicorns.forEach(unicorn => {
      unicorn.move(1)
  })
})

after(1, "second", () => {
  var unicorn2 = new Image({
    url: "./docs/images/unicorn.png",
    width: 120, 
    height: 80,
  })
  unicorns.push(unicorn2)
})
after(2, "seconds", () => {
  var unicorn3 = new Image({
    url: "./docs/images/unicorn.png",
    width: 120, 
    height: 80,
  })
  unicorns.push(unicorn3)
})
```

It still seems a little redundant to have to create each unicorn by hand. Let's use an every loop to create a new unicorn every 1 second and then add it to the unicorns list.

```javascript
var unicorns = []
every(1, "second", () => {
  var unicorn1 = new Image({
    url: "./docs/images/unicorn.png",
    width: 120, 
    height: 80,
  })
  unicorns.push(unicorn1)
})

forever(() => {
  unicorns.forEach(unicorn => {
      unicorn.move(1)
  })
})
```

**Comment by joebeachjoebeach** [comment]
That's a good idea.

I think the main hurdles are:
1. Understanding that you can / have to re-create sprites inside a function
2. Understanding that you need to have those sprites in an array in order to access them
3. Scope!

Below, I'll try to adapt the conversation I normally have with my students to be documentation-friendly:

We usually create our sprites at the beginning of our code, with something like this:
```js
var bubble = new Circle({
  radius: 50,
  color: "red",
  x: randomX(),
  y: randomY()
})
```
If I want new bubbles to appear every second, I don't actually have to create my sprites at the beginning of my code -- I can create them inside a function!
```js
every(1, "second", () => {
  var bubble = new Circle({
    radius: 50,
    color: "red",
    x: randomX(),
    y: randomY()
  })
})
```
That code _creates a new sprite every second_.

In order to do something with my bubbles (make them move, for example), I need to make an empty list to hold them: `var bubbles = []`
And each time I make a new bubble, I need to add it to the list: `bubbles.push(bubble)`
```js
// create the list
var bubbles = []

every(1, "second", () => {
  var bubble = new Circle({
    radius: 50,
    color: "red",
    x: randomX(),
    y: randomY()
  })
  // add the new bubble to the list
  bubbles.push(bubble)
})
```
Now I can use the list to talk to my bubbles and tell them what to do. In order to talk to all my bubbles, I have to use `bubbles.forEach(bubble => () {...})`

For example, let's make the bubbles always move:
```js
forever(() => {
  bubbles.forEach(bubble => {
    bubble.move(2)
  })
})
```
Let's review with a new example:

1. Create an empty list to hold your sprites:
    ```js
    var blocks = []
    ```

2. Make new sprites however often you want, and add them to the list:
    ```js
    var blocks = []

    every(2.2, "seconds", () => {
      var block = new Rectangle({
        color: "blue",
        width: 65,
        height: 30,
        x: randomX(),
        y: minY
      })
      blocks.push(block)
    })
    ```

3. Use `forEach()` to talk to your sprites and tell them what to do:
    ```js
    var blocks = []

    every(2.2, "seconds", () => {
      var block = new Rectangle({
        color: "blue",
        width: 65,
        height: 30,
        x: randomX(),
        y: minY
      })
      blocks.push(block)
    })

    forever(() => {
      blocks.forEach(block => {
        block.y += 3
      })
    })
    ```

**Comment by joebeachjoebeach** [comment]
Or! Following a similar vein as the ADEPT method, something like this:

Imagine we have a factory where we make balls.
It would be silly to just make one ball:
```js
var ball = new Circle({
  color: "green",
  radius: 25
})
```

We're a factory after all, so let's say we make a new ball every 30 seconds:
```js
every(30, "seconds", () => {
  var ball = new Circle({
    color: "green",
    radius: 25
  })
})
```

Oh no! We have a ton of balls and they're piling up everywhere! We need somewhere to put them. Let's make a box and put our balls in the box.
```js
var box = []
every(30, "seconds", () => {
  var ball = new Circle({
    color: "green",
    radius: 25
  })
  box.push(ball)
})
```
Good, now our balls are nicely organized in the box.

Now, the foreman says, "OK, you! Take the ball and throw it against the wall!"
```js
forever(() => {
  ball.move(10)
})
```
What!? Which ball? There are a lot of balls! Which one do you want me to throw? (Error!)

"Oops! Sorry! Grab the box and throw all of the balls!"
```js
forever(() => {
  box.forEach(ball => {
    ball.move(10)
  })
})
```

**Comment by stevekrouse** [comment]
I like the analogy of balls in boxes. Some ideas

* 30 seconds is a little to slow. Maybe do 3 seconds?

* We could start by throwing the first ball in the array -- `ball[0]`. And then move to all the balls. Too complicated?

**Comment by joebeachjoebeach** [comment]
- Yeah 30 seconds is definitely too slow for a Woof example
- First ball isn't a bad idea, and I don't think it'd be too complicated. Just something like this:

What!? Which ball? There are a lot of balls! Which one do you want me to throw? (Error!)

"Oops! Sorry! Grab the first ball and throw it!"
```js
forever(() => {
  box[0].move(10)
})
```

Or "Grab the first three balls and throw them!"
```js
forever(() => {
  box[0].move(10)
  box[1].move(10)
  box[2].move(10)
})
```

Or, "Grab all the balls and throw them!"
```js
forever(() => {
  box.forEach(ball => {
    ball.move(10)
  })
})
```

**Comment by stevekrouse** [comment]
Cool, I like that!
