### ISSUE TITLE
Make Clean Code button appear alongside  Error button

### ISSUE THREAD

**Issue by madduccino** [stevekrouse/WoofJS#393]
I often find myself in the situation where I have an error and it would be really helpful to format my code with the Clean Code button to better detect what's going on but I can't!

**Comment by stevekrouse** [comment]
Thanks for bringing this up! I know this is a common issue.

As you may suspect, I purposely hide the Clean Code button when there are errors. I do this because I fear what the Clean Code button will do to code that is not syntactically sound. For example, if you've forgotten a parenthesis or bracket somewhere in the middle of your code, it will improperly format all of the code below it, indenting the code below it as if it's supposed to be nested inside the unclosed block.

However, I think there's a way to solve this problem in most cases. As long as the error is a runtime error and not a syntax error, we can probably allow the user to clean code.
