### ISSUE TITLE
eslint or some other automated formatted when you save / commit

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#429]

**Comment by joebeachjoebeach** [comment]
Only just realized this issue already existed. My suggestion would be to start with eslint, then work out using prettier as we discussed before? Since Cloud 9 already uses eslint to display errors/warnings in the editor itself, and most developers working on the project are using c9, adding a .eslintrc file would be simple and have few or no side effects.

When you initialize eslint, it walks you through some questions (similar to `npm init`). Here are my guesses for those answers. Let me know if any of them should be changed.

- Are you using ES6? **Yes**
- Are you using ES6 modules? **No**
- Where will your code run (node or browser)? **Browser**
- Do you use CommonJS? **No**
- Do you use JSX? **No**
- What style of indentation do you use? **Spaces**
- What quotes do you use for strings? **Double**
- What line endings do you use? **Unix**
- Do you require semicolons? **No**
- What format do you want your config file to be in (JavaScript, YAML, JSON)? **JavaScript**

**Comment by joebeachjoebeach** [comment]
I played around with implementing a .eslintrc file in Cloud9 just to make sure this idea would be feasible, and there's one problem. Normally, eslint looks for a config file in the current directory, then traverses up through parent directories if no config file is found. So, we should be able to have a .eslintrc file in the core directory. However, .eslintrc files only work with Cloud9 if they're in the main workspace directory (~/workspace/). I'm pretty sure that most, if not all, people cloned the WoofJS directory as a subdirectory of ~/workspace/, probably something like this: ~/workspace/WoofJS/. So, any .eslintrc file we commit to the repository won't be readable by Cloud9.

Another weird thing is that for C9 to read it, the .eslintrc file must be YAML with no extension (i.e. .eslintrc.json, .eslintrc.js, .eslintrc.yml don't work, but .eslintrc formatted as YAML works).

Anyway, my conclusion from this is that integrating eslint rules into the existent C9 in-editor linting probably won't work, but we could still consider integrating it into the `npm run compile` command or a pre-commit hook.
