### ISSUE TITLE
more keyboard shortcuts in tools menu

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#448]
shortcuts for commenting out code ctl-/ and selecting the next occurrence of a word ctl-d

**Comment by stevekrouse** [comment]
Also copy and paste

**Comment by truthgoddess** [comment]
@madduccino Thoughts on what else we might add? Here's what my mind and research tells me we should add and emphasize to students that they exist:

Copy Ctrl+C
Cut Ctrl+X
Paste Ctrl+V

Select Next Occurrence Ctrl+D
Place Multiple Cursors Ctrl+LeftMouseClick

Replace Ctrl+Shift+F

Column Selection Alt+Select

Comment Code Ctrl+/

**Comment by truthgoddess** [comment]
@stevekrouse @madduccino Maddy, you told me that Steve was out of town this week, so I believe this is a safe enough issue for us to work out what we want, for me to make a branch and pull request, and let Steve add his thoughts to it after the pull request and I'll make those changes, or he (or you) can merge?

**Comment by truthgoddess** [comment]
Final list for the branch I am going to create now: 

Copy Ctrl+C
Cut Ctrl+X
Paste Ctrl+V

Select Next Occurrence Ctrl+D
Place Multiple Cursors Ctrl+LeftMouseClick

Replace Ctrl+H

Column Selection Alt+Select

Comment Code Ctrl+/

**Comment by truthgoddess** [comment]
More can be added later easily.

**Comment by truthgoddess** [comment]
Update: not going to do Copy, Cut, and Paste because of browser restrictions around those commands.

**Comment by truthgoddess** [comment]
I know this is a tiny bit of a no-no, but in working on this issue, I believe I have found an ok solution for #453. Basically, there was a previous attempt to fix that issue in which someone placed a "disabled" class to the link rather than the line item. 

I'm also currently researching how to make bootstrap menus stay up for disabled items. I think that all these things still fit within this branch, but if someone wants me to do that fix separately, let me know.

**Comment by truthgoddess** [comment]
Fixed an issue that I discovered when working with the menu. As it is the Clean Code button in the menu works, but CTRL-B doesn't work if there is no selection. It was a simple fix to get it to work, you'll see it in the pull request.

**Comment by truthgoddess** [comment]
I've tried a number of things to try and get the get next occurrence functioning to work on menu click and I can't quite figure it out. 

It seems the sublime javascript assigns the CTRL+D function to that key pair, but doesn't provide any way to access that function otherwise. I've tried using that base code to try and recreate what it does, but that hasn't been working. 

https://www.cs.princeton.edu/~dp6/CodeMirror/keymap/sublime.js

@stevekrouse If you happen to know a very quick tip here, I'd love to hear it. 

I'm going to stop trying to get that to work. The menu is looking pretty good with the functions that are there and the small fix I made. It'd be sad not to get the Crtl-D in the menu, but since I think place multiple cursors is cool, I'm going to try and think about a clever way to put things we don't want clickable there.

**Comment by truthgoddess** [comment]
@stevekrouse Actually, ignore that longer thing at the moment. I think I've figured out a good way to handle this stuff. Explanation forthcoming. 

(Forgive the over communication, but I'm following your advice: to over-communicate.)

**Comment by truthgoddess** [comment]
First, fixes and additions here:

Copy button added to tools menu (desired functionality)
Cut button added to tools menu (desired functionality)
Paste button added to tools menu (desired functionality)

Replace button added to tools menu (desired functionality)
Comment code button added to tools menu (desired functionality)

Fixed issue with CMD/CTRL-B not working if no highlighting is selected.
Fixed issue with improper disabling of clean code button (previously intended fix). This makes it even clearer that button will not work if there is an error.

Did not include the CMD/CTRL - D button for two reasons. The first was I could not figure it out. The second, after some thought, is that it is not useful to go to the menu to click the find next occurrence button multiple times because it requires too many user actions to get what they want. Other menu functions are only used one time to get the desired result. CTRL - D is better used as a keyboard shortcut. Please see #563. 

Select column was not added because it is not that useful, and alt-click on many Chromebooks is a right click. 

I'm going to double check things here to make sure I don't have uncaught problems, and then initiate a pull request. Looking forward to getting feedback.
