### ISSUE TITLE
Walk students through all variations of creating sprite1

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#484]
Currently, we just give students a textbox where they can type any name in but that's a little more freedom than they need. In reality here's what we want:

1) `sprite1.move(10)` before there's any sprites in the code. In this case we need to walk them through adding a sprite, giving it a name, and finally changing "sprite1" in the code they originally added to that name.

2)  `sprite1.move(10)` and there are one or more sprites in their code. In this case we should suggest changing the name to one of those (and possibly giving the option to create a new sprite for it, like we do in possibility 1 above). So that students would get a much better error in the following sittuation:

![screenshot 2017-09-01 at 10 16 46 am](https://user-images.githubusercontent.com/2288939/29973799-c0e9c596-8efe-11e7-8f0c-51d81c4c7011.png)

(I guess in the image above, we'd also have to advise the student to order their code better. That seems difficult... another thing to think about....)

**Comment by hallpell** [comment]
This has been marginally improved enough to not be a large issue anymore. For case 1 (dog.move() without dog defined anywhere), the error is that the variable is not defined, which pushes students to ask the right question ("how do I define dog?"). For case 2, the error is less useful, as shown in the screenshot above. This is tough enough to detect (especially due to hoisting) that I don't think a good solution is worth implementing.
