### ISSUE TITLE
Timing of error messages

### ISSUE THREAD

**Issue by madduccino** [stevekrouse/WoofJS#490]
I taught a student yesterday with the new error message design implemented (#396), and the messages got really annoying as they constantly appeared, disappeared, and changed as she typed. A pro of the error button was you could choose when to see the error message. A con was students often didn't notice it was there. A pro of the current format is you can't ignore it, but on the flip side, it is distracting. Looking for a happy medium.

**Comment by madduccino** [comment]
Example: If I write `if(` and I'm thinking about what I want to write next, the second parantheses automatically gets added and I'm bombarded with a giant error message.

![screenshot 2017-09-07 at 9 54 32 am](https://user-images.githubusercontent.com/2099441/30167009-09971aec-93b3-11e7-82b4-93978047fe43.png)

**Comment by stevekrouse** [comment]
Interesting! I can imagine it being frustrating to have a constantly changing error message, especially when 1) the error message doesn't make much sense, and 2) the errors are appearing before you're ready for them.

Problem 1 is terrible, but probably difficult to solve. Let's create another issue for that. https://github.com/stevekrouse/WoofJS/issues/491

For 2, this is tricky because if there's no button, when should we show errors? 

Currently [the code runs when there is a 1 second break in typing](https://github.com/stevekrouse/WoofJS/blob/master/create.html#L1576), and the error is updated in the same timeframe, but we could slow the error refresh rate down a bit. Let's call this solution 1.

From my perspective, I don't find the error that obnoxious as it is. It's kind of nice actually to get constant feedback about whether my program has a bug or not and what it is. We could even go further to make this explicit, telling users, "Your code is running" in green and "Your code has a bug" in red (or yellow), respectively.

One way to resolve this is to make this interface expandable and collapsable. It always shows the sentence whether the code is running or has a bug, but you can either open or collapse the message inside. Thus things won't change very much as you type unless you leave that panel open. (I'd probably leave it open for students by default so they don't realize that it opens when first learning Woof.) Let's call this solution 2.

**Comment by RickMeasham** [comment]
This has been annoying me to. We turned off Autorun so the big errors at the top don't show up. How about only doing the error check when the changed line is no longer the current line?

**Comment by stevekrouse** [comment]
Thanks for adding your perspective, @RickMeasham! Sorry to hear it's annoying you.

Only doing error checks when the changed line is no longer the current line is a reasonable solution.

**Comment by hallpell** [comment]
This is addressed in #574 and fixed in #586
