### ISSUE TITLE
Error message banner

### ISSUE THREAD

**Issue by Mifter** [stevekrouse/WoofJS#574]
When you make a mistake or type slowly an error message will appear. This is great! however, this "banner" is not really a banner because instead of going over the code it pushes it ~5 lines downward. So what ever you were working on is now in a completely different area of the screen.

**Comment by stevekrouse** [comment]
This is a great point. At the same time, I don't love the solution of always leaving a buffer at the top for potential error messages. I think the ideal solution (if technically possible) would be to shift the lines of code in the text editor up (I think but it may be down) by the appropriate amount so that it appears as if they haven't moved (only the top lines of the editor would be cut off).
