### ISSUE TITLE
Yahoo Weather Integration Broken

### ISSUE THREAD

**Issue by wendybujalski** [stevekrouse/WoofJS#587]
As you can see on this site - https://developer.yahoo.com/weather/ - Yahoo retired the weather API used by WoofJS on Thursday, Jan. 3, 2019. We should find a replacement for the WoofJS documentation.

**Comment by Wowfunhappy** [comment]
We're going to run into a problem here—I don't think there are any services left that share weather forecasts without requiring the user to obtain an api key.

Even if we're okay with having students sign up to obtain keys, because all WoofJS projects are public, the keys would be publicly accessible.
