### ISSUE TITLE
How do I create a new block?

### ISSUE THREAD

**Issue by subtra3t** [stevekrouse/WoofJS#589]
So I managed to recreate the `wait` block in javascript. How do I add this to woofjs?

**Comment by hallpell** [comment]
You'll need to add it to woof.js, following the format used (something like https://github.com/stevekrouse/WoofJS/blob/6e40e966bd583eb60ed9eb205377707bef057c9c/woof.js#L516 )

You'll also need to add it to the documentation by editing docs/index.html. It probably makes sense for it to be in Control by the after and every documentation.

Sorry it took a while to get back to you, and look forward to seeing what you put together!

**Comment by subtra3t** [comment]
Thank you! I made the respective changes and opened a pull request at #591.

**Comment by hallpell** [comment]
Thanks for your work on this! I'm unsure that this approach will end up panning out for Woof (or really in JavaScript) because we want to minimize interference between different segments of code. 

[This](https://woofjs.com/create.html#hallpell_wait_testing) project is a reasonable example of what I'm talking about. When the wait is commented out, the dog moves 10x faster than the cat. If we put the wait block in, it (properly) makes the dog wait between each step but also (improperly) makes the cat wait before it takes each step, so the dog is still moving 10x faster than the cat. This is generally because JavaScript has blocking execution, where if the while loop in the wait is running, it prevents any other code from running (and will even prevent other parts of the website from running, which makes editing code stutter).

This problem is sort of the heart of #306 , which makes me skeptical that there is a reasonable, clean solution to this. Because we'd like for the wait block to block its thread of execution, but allow other threads to keep running, and JavaScript doesn't have an obvious way to only partially stop execution.

**Comment by subtra3t** [comment]
> Thanks for your work on this! I'm unsure that this approach will end up panning out for Woof (or really in JavaScript) because we want to minimize interference between different segments of code.
> 
> [This](https://woofjs.com/create.html#hallpell_wait_testing) project is a reasonable example of what I'm talking about. When the wait is commented out, the dog moves 10x faster than the cat. If we put the wait block in, it (properly) makes the dog wait between each step but also (improperly) makes the cat wait before it takes each step, so the dog is still moving 10x faster than the cat. This is generally because JavaScript has blocking execution, where if the while loop in the wait is running, it prevents any other code from running (and will even prevent other parts of the website from running, which makes editing code stutter).
> 
> This problem is sort of the heart of #306 , which makes me skeptical that there is a reasonable, clean solution to this. Because we'd like for the wait block to block its thread of execution, but allow other threads to keep running, and JavaScript doesn't have an obvious way to only partially stop execution.


Perhaps `setTimeout` could solve this?

**Comment by hallpell** [comment]
Right, setTimeout is how JavaScript wants us to approach these time-based problems (or setInterval). Which is why the time based solutions we offer in Woof are after and every, which are just accessible names for setTimeout and setInterval respectively.
