### ISSUE TITLE
What if we just didn't use JSON syntax?

### ISSUE THREAD

**Issue by Wowfunhappy** [stevekrouse/WoofJS#620]
One of the biggest and consistent pain points for early WoofJS students is understanding the difference between JSON object notation and normal Javascript code. Children will confuse `:` with `=`, put normal code within JSON objects and vice versa, and so on.

What if the documentation just didn't contain any JSON?

In other words, instead of:

```
var unicorn = new Image({
  url: "./docs/images/unicorn.png",
  width: 120, 
  height: 80,
})
```

The documentation would have:

```
var unicorn = new Image();
unicorn.url = "./docs/images/unicorn.png"
unicorn.width = 120
unicorn.height = 80
```

Notably, the latter doesn't appear to actually work in WoofJS in the moment (which maybe should be tracked in a separate issue). The `width` and `height` take effect but the URL property does not, the image has the placeholder dog.

Regardless, I would much prefer if we used the latter in documentation, I think it would help a lot of students. We _would_ need to really encourage students to have line breaks between the "sprites" or the code could get very difficult to read.

**Comment by hallpell** [comment]
This URL code doesn't currently work because you need to call setImageURL. Though making it so changing the url call that automatically is pretty easy and I was planning on doing that anyway when I had time.

I do prefer it the way you propose - creating the objects to pass to the constructor is only a positive if we're aiming to teach that distinction between object construction and modifying it after the fact, which is not something I feel the need to teach. A quick skim through the documentation seems like we could probably pull all of it out. The only parts that I need to think through more is what to do with the extra characteristics after creating the sprite. In the text part of the documentation, it has stuff like:
`x: 50, y: -100`
`fontFamily: 'arial'`
which in the new paradigm would be somewhat replicated in motion and looks. Which I think is fine, but mulling it over a bit more before making a full shift.

**Comment by Wowfunhappy** [comment]
> A quick skim through the documentation seems like we could probably pull all of it out. The only parts that I need to think through more is what to do with the extra characteristics after creating the sprite. In the text part of the documentation, it has stuff like:
`x: 50, y: -100`
`fontFamily: 'arial'`

I may not be understanding, I don't see why you wouldn't write this as:

```
textSprite1.x = 50
textSprite1.y = -100
textSprite1.fontFamily = 'arial'`
```

If there's anything that ends up just being duplicative... personally, I've _long_ thought there's "too much" in the documentation and I'm all for cutting it down.
